In [1]:
import os 
import pandas as pd

In [2]:
os.getcwd()

'/Users/anmol'

In [4]:
df = pd.read_csv("/Users/anmol/Desktop/Bengaluru_Ride_Bookings_100k.csv")

In [5]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating
0,2026-05-02,07:14:56,BK1000000,Success,CUST500000,Auto,Nagawara,Electronic City,12.7,28.2,0,NaN,NaN,0,NaN,1372.82,1.95,4.0,4.0
1,2026-05-31,05:18:03,BK1000001,Incomplete,CUST500001,Prime Plus,Yeshwanthpur,KR Puram,NaN,NaN,0,NaN,NaN,1,Customer Demand,NaN,NaN,NaN,NaN
2,2026-05-08,23:27:34,BK1000002,Cancelled by Customer,CUST500002,Auto,Marathahalli,Yeshwanthpur,NaN,NaN,1,Wrong Address,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2026-05-28,10:19:50,BK1000003,Success,CUST500003,Mini,Jayanagar,Banaswadi,10.8,37.3,0,NaN,NaN,0,NaN,598.00,19.20,3.3,4.6
4,2026-05-14,11:00:42,BK1000004,Success,CUST500004,Auto,Whitefield,Indiranagar,13.7,11.9,0,NaN,NaN,0,NaN,630.30,5.59,4.8,3.7

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               100000 non-null  str
 1   Time                               100000 non-null  str
 2   Booking ID                         100000 non-null  str
 3   Booking Status                     100000 non-null  str
 4   Customer ID                        100000 non-null  str
 5   Vehicle Type                       100000 non-null  str
 6   Pickup Location                    100000 non-null  str
 7   Drop Location                      100000 non-null  str
 8   Avg VTAT                           62017 non-null   float64
 9   Avg CTAT                           62017 non-null   float64
 10  Cancelled Rides by Customer        100000 non-null  int64
 11  Reason for cancelling by Customer  18078 non-null   str
 12  Cancelled Rides by Driver          15034 non-null   str
 13  Incomplete Rides                   100000 non-null  int64
 14  Incomplete Rides Reason            4871 non-null    str
 15  Booking Value                      62017 non-null   float64
 16  Ride Distance                      62017 non-null   float64
 17  Driver Ratings                     62017 non-null   float64
 18  Customer Rating                    62017 non-null   float64
dtypes: float64(6), int64(2), str(11)
memory usage: 14.5 MB

In [10]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,62017.000000,62017.000000,100000.000000,100000.000000,62017.000000,62017.000000,62017.000000,62017.000000
mean,8.480447,35.075961,0.180780,0.048710,788.593034,17.982692,4.004544,3.999911
std,3.761995,14.464484,0.384838,0.215262,410.097347,9.814321,0.577595,0.577417
min,2.000000,10.000000,0.000000,0.000000,80.020000,1.000000,3.000000,3.000000
25%,5.200000,22.500000,0.000000,0.000000,432.900000,9.520000,3.500000,3.500000
50%,8.500000,35.200000,0.000000,0.000000,788.110000,17.970000,4.000000,4.000000
75%,11.700000,47.500000,0.000000,0.000000,1143.550000,26.470000,4.500000,4.500000
max,15.000000,60.000000,1.000000,1.000000,1499.990000,35.000000,5.000000,5.000000

In [12]:
duplicates = df[df.duplicated()]
total_duplicates = df.duplicated().sum()

print(total_duplicates)
print(duplicates)

0
Empty DataFrame
Columns: [Date, Time, Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating]
Index: []

In [23]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [24]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avg_vtat',
       'avg_ctat', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'ride_distance', 'driver_ratings', 'customer_rating'],
      dtype='str')

In [25]:
df.isnull().sum()

date                                     0
time                                     0
booking_id                               0
booking_status                           0
customer_id                              0
vehicle_type                             0
pickup_location                          0
drop_location                            0
avg_vtat                             37983
avg_ctat                             37983
cancelled_rides_by_customer              0
reason_for_cancelling_by_customer    81922
cancelled_rides_by_driver            84966
incomplete_rides                         0
incomplete_rides_reason              95129
booking_value                        37983
ride_distance                        37983
driver_ratings                       37983
customer_rating                      37983
dtype: int64

In [35]:
df['avg_vtat'] = df['avg_vtat'].fillna(df['avg_vtat'].median())

In [36]:
df['avg_ctat'] = df['avg_ctat'].fillna(df['avg_ctat'].median())

In [37]:
df.isnull().sum()

date                                     0
time                                     0
booking_id                               0
booking_status                           0
customer_id                              0
vehicle_type                             0
pickup_location                          0
drop_location                            0
avg_vtat                                 0
avg_ctat                                 0
cancelled_rides_by_customer              0
reason_for_cancelling_by_customer    81922
cancelled_rides_by_driver            84966
incomplete_rides                         0
incomplete_rides_reason              95129
booking_value                        37983
ride_distance                        37983
driver_ratings                       37983
customer_rating                      37983
dtype: int64

In [41]:
df["cancelled_rides_by_driver"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
99995    NaN
99996    NaN
99997    NaN
99998    NaN
99999    NaN
Name: cancelled_rides_by_driver, Length: 100000, dtype: str

In [43]:
df['reason_for_cancelling_by_customer'] = (
    df['reason_for_cancelling_by_customer']
    .fillna('Not Cancelled')
)

In [44]:
df['reason_for_cancelling_by_customer']

0                                  Not Cancelled
1                                  Not Cancelled
2                                  Wrong Address
3                                  Not Cancelled
4                                  Not Cancelled
                          ...
99995                            Change of plans
99996    AC is not working (Only for 4-wheelers)
99997                     Driver asked to cancel
99998                              Not Cancelled
99999                              Not Cancelled
Name: reason_for_cancelling_by_customer, Length: 100000, dtype: str

In [46]:
df.isnull().sum()

date                                     0
time                                     0
booking_id                               0
booking_status                           0
customer_id                              0
vehicle_type                             0
pickup_location                          0
drop_location                            0
avg_vtat                                 0
avg_ctat                                 0
cancelled_rides_by_customer              0
reason_for_cancelling_by_customer        0
cancelled_rides_by_driver            84966
incomplete_rides                         0
incomplete_rides_reason              95129
booking_value                        37983
ride_distance                        37983
driver_ratings                       37983
customer_rating                      37983
dtype: int64

In [54]:
df["cancelled_rides_by_driver"] = (
    df['cancelled_rides_by_driver']
    .fillna('Not Cancelled')
)

In [55]:
df.isnull().sum()

date                                     0
time                                     0
booking_id                               0
booking_status                           0
customer_id                              0
vehicle_type                             0
pickup_location                          0
drop_location                            0
avg_vtat                                 0
avg_ctat                                 0
cancelled_rides_by_customer              0
reason_for_cancelling_by_customer        0
cancelled_rides_by_driver                0
incomplete_rides                         0
incomplete_rides_reason              95129
booking_value                        37983
ride_distance                        37983
driver_ratings                       37983
customer_rating                      37983
dtype: int64

In [56]:
df["booking_value"] = df["booking_value"].fillna(df["booking_value"].mean())
df["ride_distance"] = df["ride_distance"].fillna(df["ride_distance"].mean())
df["driver_ratings"] = df["driver_ratings"].fillna(df["driver_ratings"].mean())
df["customer_rating"] = df["customer_rating"].fillna(df["customer_rating"].mean())

In [57]:
df.isnull().sum()

date                                     0
time                                     0
booking_id                               0
booking_status                           0
customer_id                              0
vehicle_type                             0
pickup_location                          0
drop_location                            0
avg_vtat                                 0
avg_ctat                                 0
cancelled_rides_by_customer              0
reason_for_cancelling_by_customer        0
cancelled_rides_by_driver                0
incomplete_rides                         0
incomplete_rides_reason              95129
booking_value                            0
ride_distance                            0
driver_ratings                           0
customer_rating                          0
dtype: int64

In [59]:
df['incomplete_rides_reason'] = (
    df['incomplete_rides_reason']
    .fillna('Complete')
)

In [60]:
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,cancelled_rides_by_customer,reason_for_cancelling_by_customer,cancelled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,ride_distance,driver_ratings,customer_rating
0,2026-05-02,07:14:56,BK1000000,Success,CUST500000,Auto,Nagawara,Electronic City,12.7,28.2,0,Not Cancelled,Not Cancelled,0,Complete,1372.820000,1.950000,4.000000,4.000000
1,2026-05-31,05:18:03,BK1000001,Incomplete,CUST500001,Prime Plus,Yeshwanthpur,KR Puram,8.5,35.2,0,Not Cancelled,Not Cancelled,1,Customer Demand,788.593034,17.982692,4.004544,3.999911
2,2026-05-08,23:27:34,BK1000002,Cancelled by Customer,CUST500002,Auto,Marathahalli,Yeshwanthpur,8.5,35.2,1,Wrong Address,Not Cancelled,0,Complete,788.593034,17.982692,4.004544,3.999911
3,2026-05-28,10:19:50,BK1000003,Success,CUST500003,Mini,Jayanagar,Banaswadi,10.8,37.3,0,Not Cancelled,Not Cancelled,0,Complete,598.000000,19.200000,3.300000,4.600000
4,2026-05-14,11:00:42,BK1000004,Success,CUST500004,Auto,Whitefield,Indiranagar,13.7,11.9,0,Not Cancelled,Not Cancelled,0,Complete,630.300000,5.590000,4.800000,3.700000

In [61]:
df.isnull().sum()

date                                 0
time                                 0
booking_id                           0
booking_status                       0
customer_id                          0
vehicle_type                         0
pickup_location                      0
drop_location                        0
avg_vtat                             0
avg_ctat                             0
cancelled_rides_by_customer          0
reason_for_cancelling_by_customer    0
cancelled_rides_by_driver            0
incomplete_rides                     0
incomplete_rides_reason              0
booking_value                        0
ride_distance                        0
driver_ratings                       0
customer_rating                      0
dtype: int64

In [62]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.0.49)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [65]:

from sqlalchemy import create_engine
from urllib.parse import quote_plus


# MySQL connection details
username = "root"
password = quote_plus("Root@1234")  # Encode special characters
host = "localhost"
port = 3306
database = "Bengluru_ride_Booking"

# Create connection
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Test connection
with engine.connect() as conn:
    print("Connected to MySQL successfully!")

# Write DataFrame to MySQL
table_name = "ride_data"

df.to_sql(
    table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print(f"Table '{table_name}' created successfully!")

# Read sample rows back from MySQL
sample_df = pd.read_sql(
    f"SELECT * FROM {table_name} LIMIT 5",
    con=engine
)

print(sample_df)

Connected to MySQL successfully!
Table 'ride_data' created successfully!
         date      time booking_id         booking_status customer_id  \
0  2026-05-02  07:14:56  BK1000000                Success  CUST500000
1  2026-05-31  05:18:03  BK1000001             Incomplete  CUST500001
2  2026-05-08  23:27:34  BK1000002  Cancelled by Customer  CUST500002
3  2026-05-28  10:19:50  BK1000003                Success  CUST500003
4  2026-05-14  11:00:42  BK1000004                Success  CUST500004

  vehicle_type pickup_location    drop_location  avg_vtat  avg_ctat  \
0         Auto        Nagawara  Electronic City      12.7      28.2
1   Prime Plus    Yeshwanthpur         KR Puram       8.5      35.2
2         Auto    Marathahalli     Yeshwanthpur       8.5      35.2
3         Mini       Jayanagar        Banaswadi      10.8      37.3
4         Auto      Whitefield      Indiranagar      13.7      11.9

   cancelled_rides_by_customer reason_for_cancelling_by_customer  \
0                            0                     Not Cancelled
1                            0                     Not Cancelled
2                            1                     Wrong Address
3                            0                     Not Cancelled
4                            0                     Not Cancelled

  cancelled_rides_by_driver  incomplete_rides incomplete_rides_reason  \
0             Not Cancelled                 0                Complete
1             Not Cancelled                 1         Customer Demand
2             Not Cancelled                 0                Complete
3             Not Cancelled                 0                Complete
4             Not Cancelled                 0                Complete

   booking_value  ride_distance  driver_ratings  customer_rating
0    1372.820000       1.950000        4.000000         4.000000
1     788.593034      17.982692        4.004544         3.999911
2     788.593034      17.982692        4.004544         3.999911
3     598.000000      19.200000        3.300000         4.600000
4     630.300000       5.590000        4.800000         3.700000